
export const states = [
    { name: "Andhra Pradesh" },
    { name: "Arunachal Pradesh" },
    { name: "Assam" },
    { name: "Bihar" },
    { name: "Chhattisgarh" },
    { name: "Goa" },
    { name: "Gujarat" },
    { name: "Haryana" },
    { name: "Himachal Pradesh" },
    { name: "Jharkhand" },
    { name: "Karnataka" },
    { name: "Kerala" },
    { name: "Madhya Pradesh" },
    { name: "Maharashtra" },
    { name: "Manipur" },
    { name: "Meghalaya" },
    { name: "Mizoram" },
    { name: "Nagaland" },
    { name: "Odisha" },
    { name: "Punjab" },
    { name: "Rajasthan" },
    { name: "Sikkim" },
    { name: "Tamil Nadu" },
    { name: "Telangana" },
    { name: "Tripura" },
    { name: "Uttar Pradesh" },
    { name: "Uttarakhand" },
    { name: "West Bengal" },
    { name: "Andaman and Nicobar Islands" },
    { name: "Chandigarh" },
    { name: "Dadra and Nagar Haveli and Daman and Diu" },
    { name: "Delhi" },
    { name: "Jammu and Kashmir" },
    { name: "Ladakh" },
    { name: "Lakshadweep" },
    { name: "Puducherry" },
];

export const cities = [
  // Andhra Pradesh
  { name: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Vijayawada", state: "Andhra Pradesh" },
  { name: "Tirupati", state: "Andhra Pradesh" },
  { name: "Guntur", state: "Andhra Pradesh" },
  { name: "Nellore", state: "Andhra Pradesh" },
  { name: "Kurnool", state: "Andhra Pradesh" },
  { name: "Rajahmundry", state: "Andhra Pradesh" },
  { name: "Kakinada", state: "Andhra Pradesh" },
  { name: "Anantapur", state: "Andhra Pradesh" },
  { name: "Amaravati", state: "Andhra Pradesh" },
  // Arunachal Pradesh
  { name: "Itanagar", state: "Arunachal Pradesh" },
  { name: "Tawang", state: "Arunachal Pradesh" },
  { name: "Ziro", state: "Arunachal Pradesh" },
  { name: "Bomdila", state: "Arunachal Pradesh" },
  { name: "Pasighat", state: "Arunachal Pradesh" },
  // Assam
  { name: "Guwahati", state: "Assam" },
  { name: "Dibrugarh", state: "Assam" },
  { name: "Silchar", state: "Assam" },
  { name: "Jorhat", state: "Assam" },
  { name: "Tezpur", state: "Assam" },
  // Bihar
  { name: "Patna", state: "Bihar" },
  { name: "Gaya", state: "Bihar" },
  { name: "Bodh Gaya", state: "Bihar" },
  { name: "Nalanda", state: "Bihar" },
  { name: "Munger", state: "Bihar" },
  // Chhattisgarh
  { name: "Raipur", state: "Chhattisgarh" },
  { name: "Bhilai", state: "Chhattisgarh" },
  { name: "Bilaspur", state: "Chhattisgarh" },
  { name: "Jagdalpur", state: "Chhattisgarh" },
  // Goa
  { name: "Panaji", state: "Goa" },
  { name: "Margao", state: "Goa" },
  { name: "Vasco da Gama", state: "Goa" },
  { name: "Mapusa", state: "Goa" },
  { name: "Ponda", state: "Goa" },
  // Gujarat
  { name: "Ahmedabad", state: "Gujarat" },
  { name: "Surat", state: "Gujarat" },
  { name: "Vadodara", state: "Gujarat" },
  { name: "Rajkot", state: "Gujarat" },
  { name: "Bhuj", state: "Gujarat" },
  { name: "Dwarka", state: "Gujarat" },
  // Haryana
  { name: "Gurugram", state: "Haryana" },
  { name: "Faridabad", state: "Haryana" },
  { name: "Chandigarh", state: "Haryana" },
  { name: "Hisar", state: "Haryana" },
  { name: "Karnal", state: "Haryana" },
  // Himachal Pradesh
  { name: "Shimla", state: "Himachal Pradesh" },
  { name: "Manali", state: "Himachal Pradesh" },
  { name: "Dharamshala", state: "Himachal Pradesh" },
  { name: "Kullu", state: "Himachal Pradesh" },
  { name: "Dalhousie", state: "Himachal Pradesh" },
  // Jharkhand
  { name: "Ranchi", state: "Jharkhand" },
  { name: "Jamshedpur", state: "Jharkhand" },
  { name: "Dhanbad", state: "Jharkhand" },
  { name: "Bokaro", state: "Jharkhand" },
  // Karnataka
  { name: "Bengaluru", state: "Karnataka" },
  { name: "Mysuru", state: "Karnataka" },
  { name: "Mangaluru", state: "Karnataka" },
  { name: "Hubballi", state: "Karnataka" },
  { name: "Hampi", state: "Karnataka" },
  { name: "Udupi", state: "Karnataka" },
  // Kerala
  { name: "Kochi", state: "Kerala" },
  { name: "Thiruvananthapuram", state: "Kerala" },
  { name: "Kozhikode", state: "Kerala" },
  { name: "Alleppey", state: "Kerala" },
  { name: "Munnar", state: "Kerala" },
  // Madhya Pradesh
  { name: "Indore", state: "Madhya Pradesh" },
  { name: "Bhopal", state: "Madhya Pradesh" },
  { name: "Jabalpur", state: "Madhya Pradesh" },
  { name: "Gwalior", state: "Madhya Pradesh" },
  { name: "Ujjain", state: "Madhya Pradesh" },
  { name: "Khajuraho", state: "Madhya Pradesh" },
  // Maharashtra
  { name: "Mumbai", state: "Maharashtra" },
  { name: "Pune", state: "Maharashtra" },
  { name: "Nagpur", state: "Maharashtra" },
  { name: "Aurangabad", state: "Maharashtra" },
  { name: "Nashik", state: "Maharashtra" },
  { name: "Mahabaleshwar", state: "Maharashtra" },
  // Manipur
  { name: "Imphal", state: "Manipur" },
  { name: "Ukhrul", state: "Manipur" },
  // Meghalaya
  { name: "Shillong", state: "Meghalaya" },
  { name: "Cherrapunji", state: "Meghalaya" },
  { name: "Mawlynnong", state: "Meghalaya" },
  // Mizoram
  { name: "Aizawl", state: "Mizoram" },
  { name: "Lunglei", state: "Mizoram" },
  // Nagaland
  { name: "Kohima", state: "Nagaland" },
  { name: "Dimapur", state: "Nagaland" },
  // Odisha
  { name: "Bhubaneswar", state: "Odisha" },
  { name: "Puri", state: "Odisha" },
  { name: "Cuttack", state: "Odisha" },
  { name: "Konark", state: "Odisha" },
  // Punjab
  { name: "Amritsar", state: "Punjab" },
  { name: "Ludhiana", state: "Punjab" },
  { name: "Jalandhar", state: "Punjab" },
  { name: "Patiala", state: "Punjab" },
  { name: "Chandigarh", state: "Punjab" },
  // Rajasthan
  { name: "Jaipur", state: "Rajasthan" },
  { name: "Udaipur", state: "Rajasthan" },
  { name: "Jodhpur", state: "Rajasthan" },
  { name: "Jaisalmer", state: "Rajasthan" },
  { name: "Pushkar", state: "Rajasthan" },
  { name: "Bikaner", state: "Rajasthan" },
  // Sikkim
  { name: "Gangtok", state: "Sikkim" },
  { name: "Pelling", state: "Sikkim" },
  { name: "Lachung", state: "Sikkim" },
  // Tamil Nadu
  { name: "Chennai", state: "Tamil Nadu" },
  { name: "Coimbatore", state: "Tamil Nadu" },
  { name: "Madurai", state: "Tamil Nadu" },
  { name: "Kanyakumari", state: "Tamil Nadu" },
  { name: "Ooty", state: "Tamil Nadu" },
  { name: "Rameswaram", state: "Tamil Nadu" },
  // Telangana
  { name: "Hyderabad", state: "Telangana" },
  { name: "Warangal", state: "Telangana" },
  { name: "Nizamabad", state: "Telangana" },
  // Tripura
  { name: "Agartala", state: "Tripura" },
  { name: "Udaipur", state: "Tripura" },
  // Uttar Pradesh
  { name: "Lucknow", state: "Uttar Pradesh" },
  { name: "Agra", state: "Uttar Pradesh" },
  { name: "Varanasi", state: "Uttar Pradesh" },
  { name: "Allahabad", state: "Uttar Pradesh" },
  { name: "Kanpur", state: "Uttar Pradesh" },
  { name: "Mathura", state: "Uttar Pradesh" },
  { name: "Meerut", state: "Uttar Pradesh" },
  { name: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Noida", state: "Uttar Pradesh" },
  { name: "Muzaffarnagar", state: "Uttar Pradesh" },
  // Uttarakhand
  { name: "Dehradun", state: "Uttarakhand" },
  { name: "Rishikesh", state: "Uttarakhand" },
  { name: "Haridwar", state: "Uttarakhand" },
  { name: "Nainital", state: "Uttarakhand" },
  { name: "Mussoorie", state: "Uttarakhand" },
  { name: "Roorkee", state: "Uttarakhand" },
  // West Bengal
  { name: "Kolkata", state: "West Bengal" },
  { name: "Darjeeling", state: "West Bengal" },
  { name: "Siliguri", state: "West Bengal" },
  { name: "Durgapur", state: "West Bengal" },
  // Andaman and Nicobar Islands
  { name: "Port Blair", state: "Andaman and Nicobar Islands" },
  { name: "Havelock Island", state: "Andaman and Nicobar Islands" },
  // Chandigarh
  { name: "Chandigarh", state: "Chandigarh" },
  // Dadra and Nagar Haveli and Daman and Diu
  { name: "Daman", state: "Dadra and Nagar Haveli and Daman and Diu" },
  { name: "Diu", state: "Dadra and Nagar Haveli and Daman and Diu" },
  { name: "Silvassa", state: "Dadra and Nagar Haveli and Daman and Diu" },
  // Delhi
  { name: "New Delhi", state: "Delhi" },
  // Jammu and Kashmir
  { name: "Srinagar", state: "Jammu and Kashmir" },
  { name: "Jammu", state: "Jammu and Kashmir" },
  { name: "Gulmarg", state: "Jammu and Kashmir" },
  { name: "Pahalgam", state: "Jammu and Kashmir" },
  // Ladakh
  { name: "Leh", state: "Ladakh" },
  { name: "Kargil", state: "Ladakh" },
  // Lakshadweep
  { name: "Kavaratti", state: "Lakshadweep" },
  // Puducherry
  { name: "Puducherry", state: "Puducherry" },
];

const stateTranslations: Record<string, Partial<Record<string, string>>> = {
  hi: {
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Arunachal Pradesh": "अरुणाचल प्रदेश",
    Assam: "असम",
    Bihar: "बिहार",
    Chhattisgarh: "छत्तीसगढ़",
    Goa: "गोवा",
    Gujarat: "गुजरात",
    Haryana: "हरियाणा",
    "Himachal Pradesh": "हिमाचल प्रदेश",
    Jharkhand: "झारखंड",
    Karnataka: "कर्नाटक",
    Kerala: "केरल",
    "Madhya Pradesh": "मध्य प्रदेश",
    Maharashtra: "महाराष्ट्र",
    Manipur: "मणिपुर",
    Meghalaya: "मेघालय",
    Mizoram: "मिजोरम",
    Nagaland: "नागालैंड",
    Odisha: "ओडिशा",
    Punjab: "पंजाब",
    Rajasthan: "राजस्थान",
    Sikkim: "सिक्किम",
    "Tamil Nadu": "तमिलनाडु",
    Telangana: "तेलंगाना",
    Tripura: "त्रिपुरा",
    "Uttar Pradesh": "उत्तर प्रदेश",
    Uttarakhand: "उत्तराखंड",
    "West Bengal": "पश्चिम बंगाल",
    "Andaman and Nicobar Islands": "अंडमान और निकोबार द्वीपसमूह",
    Chandigarh: "चंडीगढ़",
    "Dadra and Nagar Haveli and Daman and Diu": "दादरा और नगर हवेली और दमन और दीव",
    Delhi: "दिल्ली",
    "Jammu and Kashmir": "जम्मू और कश्मीर",
    Ladakh: "लद्दाख",
    Lakshadweep: "लक्षद्वीप",
    Puducherry: "पुडुचेरी",
  },
};

const cityTranslations: Record<string, Partial<Record<string, string>>> = {
  hi: {
    Visakhapatnam: "विशाखापट्टनम",
    Vijayawada: "विजयवाड़ा",
    Tirupati: "तिरुपति",
    Guntur: "गुंटूर",
    Nellore: "नेल्लोर",
    Kurnool: "कुरनूल",
    Rajahmundry: "राजमुंदरी",
    Kakinada: "काकीनाडा",
    Anantapur: "अनंतपुर",
    Amaravati: "अमरावती",
    Itanagar: "ईटानगर",
    Tawang: "तवांग",
    Ziro: "ज़ीरो",
    Bomdila: "बोमडिला",
    Pasighat: "पासीघाट",
    Guwahati: "गुवाहाटी",
    Dibrugarh: "डिब्रूगढ़",
    Silchar: "सिलचर",
    Jorhat: "जोरहाट",
    Tezpur: "तेजपुर",
    Patna: "पटना",
    Gaya: "गया",
    "Bodh Gaya": "बोध गया",
    Nalanda: "नालंदा",
    Munger: "मुंगेर",
    Raipur: "रायपुर",
    Bhilai: "भिलाई",
    Bilaspur: "बिलासपुर",
    Jagdalpur: "जगदलपुर",
    Panaji: "पणजी",
    Margao: "मडगांव",
    "Vasco da Gama": "वास्को द गामा",
    Mapusa: "मापुसा",
    Ponda: "पोंडा",
    Ahmedabad: "अहमदाबाद",
    Surat: "सूरत",
    Vadodara: "वडोदरा",
    Rajkot: "राजकोट",
    Bhuj: "भुज",
    Dwarka: "द्वारका",
    Gurugram: "गुरुग्राम",
    Faridabad: "फरीदाबाद",
    Chandigarh: "चंडीगढ़",
    Hisar: "हिसार",
    Karnal: "करनाल",
    Shimla: "शिमला",
    Manali: "मनाली",
    Dharamshala: "धर्मशाला",
    Kullu: "कुल्लू",
    Dalhousie: "डलहौज़ी",
    Ranchi: "रांची",
    Jamshedpur: "जमशेदपुर",
    Dhanbad: "धनबाद",
    Bokaro: "बोकारो",
    Bengaluru: "बेंगलुरु",
    Mysuru: "मैसूरु",
    Mangaluru: "मंगलुरु",
    Hubballi: "हुब्बल्ली",
    Hampi: "हम्पी",
    Udupi: "उडुपी",
    Kochi: "कोच्चि",
    Thiruvananthapuram: "तिरुवनंतपुरम",
    Kozhikode: "कोझिकोड",
    Alleppey: "अलेप्पी",
    Munnar: "मुन्नार",
    Indore: "इंदौर",
    Bhopal: "भोपाल",
    Jabalpur: "जबलपुर",
    Gwalior: "ग्वालियर",
    Ujjain: "उज्जैन",
    Khajuraho: "खजुराहो",
    Mumbai: "मुंबई",
    Pune: "पुणे",
    Nagpur: "नागपुर",
    Aurangabad: "औरंगाबाद",
    Nashik: "नासिक",
    Mahabaleshwar: "महाबलेश्वर",
    Imphal: "इम्फाल",
    Ukhrul: "उखरुल",
    Shillong: "शिलांग",
    Cherrapunji: "चेरापूंजी",
    Mawlynnong: "मावलिनॉन्ग",
    Aizawl: "आइजोल",
    Lunglei: "लुंगलेई",
    Kohima: "कोहिमा",
    Dimapur: "दीमापुर",
    Bhubaneswar: "भुवनेश्वर",
    Puri: "पुरी",
    Cuttack: "कटक",
    Konark: "कोणार्क",
    Amritsar: "अमृतसर",
    Ludhiana: "लुधियाना",
    Jalandhar: "जालंधर",
    Patiala: "पटियाला",
    Jaipur: "जयपुर",
    Udaipur: "उदयपुर",
    Jodhpur: "जोधपुर",
    Jaisalmer: "जैसलमेर",
    Pushkar: "पुष्कर",
    Bikaner: "बीकानेर",
    Gangtok: "गंगटोक",
    Pelling: "पेलिंग",
    Lachung: "लाचुंग",
    Chennai: "चेन्नई",
    Coimbatore: "कोयंबटूर",
    Madurai: "मदुरै",
    Kanyakumari: "कन्याकुमारी",
    Ooty: "ऊटी",
    Rameswaram: "रामेश्वरम",
    Hyderabad: "हैदराबाद",
    Warangal: "वरंगल",
    Nizamabad: "निज़ामाबाद",
    Agartala: "अगरतला",
    Lucknow: "लखनऊ",
    Agra: "आगरा",
    Varanasi: "वाराणसी",
    Allahabad: "इलाहाबाद",
    Kanpur: "कानपुर",
    Mathura: "मथुरा",
    Meerut: "मेरठ",
    Ghaziabad: "गाज़ियाबाद",
    Noida: "नोएडा",
    Muzaffarnagar: "मुज़फ्फरनगर",
    Dehradun: "देहरादून",
    Rishikesh: "ऋषिकेश",
    Haridwar: "हरिद्वार",
    Nainital: "नैनीताल",
    Mussoorie: "मसूरी",
    Roorkee: "रुड़की",
    Kolkata: "कोलकाता",
    Darjeeling: "दार्जिलिंग",
    Siliguri: "सिलीगुड़ी",
    Durgapur: "दुर्गापुर",
    "Port Blair": "पोर्ट ब्लेयर",
    "Havelock Island": "हैवलॉक द्वीप",
    Daman: "दमन",
    Diu: "दीव",
    Silvassa: "सिलवासा",
    "New Delhi": "नई दिल्ली",
    Srinagar: "श्रीनगर",
    Jammu: "जम्मू",
    Gulmarg: "गुलमर्ग",
    Pahalgam: "पहलगाम",
    Leh: "लेह",
    Kargil: "कारगिल",
    Kavaratti: "कवरत्ती",
    Puducherry: "पुडुचेरी",
  },
};

function translateLocationPart(
  value: string,
  language: string,
  dictionary: Record<string, Partial<Record<string, string>>>
) {
  return dictionary[language]?.[value] ?? value;
}

export function getLocalizedLocationLabel(
  city: { name: string; state: string },
  language: string
) {
  const localizedCity = translateLocationPart(city.name, language, cityTranslations);
  const localizedState = translateLocationPart(city.state, language, stateTranslations);
  return `${localizedCity}, ${localizedState}`;
}

export function getLocalizedCityOptions(language: string) {
  return cities.map((city) => ({
    value: `${city.name}, ${city.state}`,
    label: getLocalizedLocationLabel(city, language),
  }));
}
